### ISSUE TITLE
cvmfs_env_variables for default.local

### ISSUE THREAD

**Issue by jcpunk** [cvmfs/puppet-cvmfs#23]
Right now there is no way to pass values into default.local env_variables.

Can this be added as an optional arg to init.pp?

**Comment by traylenator** [comment]
You mean the *cvmfs_env_variable* that we have on mount and domain types?

**Comment by jcpunk** [comment]
correct, for FNAL I've been asked to set a few values there.

**Comment by traylenator** [comment]
@jcpunk I'm pretty close to merging in the zerotype branch now which includes this fix as well as bunch of other stuff.

**Comment by jcpunk** [comment]
That would be wonderful.
