### ISSUE TITLE
coveralls.io support?

### ISSUE THREAD

**Issue by jcpunk** [cvmfs/puppet-cvmfs#25]
With the increase in tests with the zerotype branch, it might be worth adding coveralls.io hooks to locate under tested code.

**Comment by traylenator** [comment]
Main thing missing is concated files are not tested for content.... I need to look in acceptance tests.

**Comment by traylenator** [comment]
The beaker branch now has one acceptance test. $(ls /cvmfs/atlas.cern.ch)

```bash
BEAKER_debug=yes bundle exec rspec spec/acceptance
```

**Comment by traylenator** [comment]
I'm never actually going to do anything here, I know there are lots of missing tests,
