### ISSUE TITLE
v0.4.3 unable to resolve dependency 'erwbgy-limits' (>=1.0.0)

### ISSUE THREAD

**Issue by jcpunk** [cvmfs/puppet-cvmfs#26]
$ puppet module install CERNOps-cvmfs
Preparing to install into /home/jcpunk/.puppet/modules ...
Downloading from http://forge.puppetlabs.com ...
Error: Could not install module 'CERNOps-cvmfs' (latest: v0.4.3)
  No version of 'erwbgy-limits' will satisfy dependencies
    'CERNOps-cvmfs' (v0.4.3) requires 'erwbgy-limits' (>=1.0.0)
    Use `puppet module install --ignore-dependencies` to install only this module

https://forge.puppetlabs.com/erwbgy/limits shows latest version is 0.3.1

**Comment by traylenator** [comment]
Thanks @jcpunk
