### ISSUE TITLE
Client configuration in README.md provides invalid example

### ISSUE THREAD

**Issue by jcpunk** [cvmfs/puppet-cvmfs#28]
## Client Configuration
To configure a cvmfs client enable the module

```puppet
class{cvmfs:
}
```
or 

```puppet
class{'cvmfs':
  cvmfs_quota      => 100
  cvmfs_server_url => 'http://web.example.org/cvmfs/cmfs.example.org'  # this line doesn't work
}
```

the second example reports no `cvmfs_server_url` option to init.pp

**Comment by jcpunk** [comment]
The overall answer is probably related to PR#24's resolution

**Comment by traylenator** [comment]
Indeed. I guess we want document one manual way and a couple of examples of
enabling cvmfs-config.

**Comment by jcpunk** [comment]
And depending on how PR#24 plays out, some clear way of setting CVMFS_SERVER_URL in default.local
