### ISSUE TITLE
Improve error message when running at CERN an pluginsync is in operation.

### ISSUE THREAD

**Issue by traylenator** [cvmfs/puppet-cvmfs#49]
Only at CERN you get

Notice: /Stage[main]/Cvmfs/Notify[cvmfs has not been configured, one more puppet run required.]/message: defined 'message' as 'cvmfs has not been configured, one more puppet run required.'

if pluginsync does not have cvmfs in it .

Improve error message.

Steve.

**Comment by Aris-Breezy** [comment]
I think this should be closed by now, since  CVMFS v.2.2 ~ , we run CVMFS only one time.

**Comment by traylenator** [comment]
I don't even know how to fix this. It's really a puppet problem.
