### ISSUE TITLE
CVMFS_CLAIM_OWNERSHIP for clients

### ISSUE THREAD

**Issue by mboisson** [cvmfs/puppet-cvmfs#62]
Hi,
Is there a way to support CVMFS_CLAIM_OWNSERHIP=no  for clients ?

Maxime Boissonneault

**Comment by mboisson** [comment]
In fact, looking for the code yesterday, it seems to set CVMFS_CLAIM_OWNERSHIP in the client.conf : 

```
[mboisson@build-node puppet-cvmfs]$ grep -ri ownership .
./README.md:* `claim_ownership`. By default false if true it enables the `CVMFS_CLAIM_OWNERSHIP` option the server's client instance.
./manifests/zero.pp:  $claim_ownership = false,
./templates/client.conf.erb:<% if @claim_ownership -%>
./templates/client.conf.erb:CVMFS_CLAIM_OWNERSHIP=yes
```

However, the documentation talks about the server... 

Moreover, it says that the default is CVMFS_CLAIM_OWNERSHIP=no, but when you install the CVMFS client, the default value is yes in default.local. 

``` 
[root@cvmfs-client cvmfs]# grep -ri owner .
./default.conf:CVMFS_CLAIM_OWNERSHIP=yes
``` 

Therefore, the current code probably does not work even if it is for the client. 

Or is there something I don't understand in the code ?

**Comment by traylenator** [comment]
So that's the **special** cvmfs client on the cvmfs servers it can be set for. 
It can't be set for the normal every day clients as thigns stand.

**Comment by mboisson** [comment]
Ah, I see. 

Well, if you give me pointers as to what would need to be changed, I can try a patch, but I don't know this code and I am no puppet expert.

**Comment by mboisson** [comment]
Ok, I *think* that PR #63 is what I had to do.

**Comment by traylenator** [comment]
Was fixed with https://github.com/cvmfs/puppet-cvmfs/pull/63
