### ISSUE TITLE
non-existent option CVMFS_FORCE_SIGNING  is set automatically

### ISSUE THREAD

**Issue by rptaylor** [cvmfs/puppet-cvmfs#66]
It seems the puppet module sets CVMFS_FORCE_SIGNING='yes'.
I don't see that coming from anywhere in our config so the CVMFS puppet module seems to be doing it automatically.

This does not appear to be a documented or supported option of the CVMFS client. If it ever existed, it does not anymore. With the setting in the config file, you can see that it is not recognized:
cvmfs_config showconfig | grep CVMFS_FORCE_SIGNING

So I would think that anything related to CVMFS_FORCE_SIGNING should be removed from the Puppet module.

**Comment by traylenator** [comment]
Agreed I find no record of this. @jblomer did this used to be an option or ....

**Comment by jblomer** [comment]
@traylenator it was an option very early in cvmfs but it has no meaning for many years.
