### ISSUE TITLE
Default SELinux context is incorrect. 

### ISSUE THREAD

**Issue by kalvaer** [cvmfs/puppet-cvmfs#68]
As per https://github.com/cvmfs/cvmfs/pull/549 
CVMFS now has a different default context type.
With SELinux enabled, this can cause CVMFS to fail.

ie: 
```
Notice: /Stage[main]/Cvmfs::Install/File[/build1/cvmfs]/ensure: created
Notice: Applied catalog in 20.84 seconds
[root@pmjptppyum6 ~]# cvmfs_config chksetup
Warning: SELinux enabled, but cache directory (/build1/cvmfs) labeled 'var_lib_t' instead of 'cvmfs_cache_t'
[root@pmjptppyum6 ~]# cvmfs_config probe
Probing /cvmfs/atlas-condb.cern.ch... Failed!
Probing /cvmfs/atlas-nightlies.cern.ch... Failed!
Probing /cvmfs/atlas.cern.ch... Failed!
```

Patch file attached

[set_default_secontext.patch.txt](https://github.com/cvmfs/puppet-cvmfs/files/1454015/set_default_secontext.patch.txt)

**Comment by traylenator** [comment]
@jblomer had a look through changelog but could not see when and where changed?

**Comment by jblomer** [comment]
@traylenator This was part of cvmfs 2.1.20, there is a changelog entry

    Use custom cvmfs_cache_t SELinux label for the cache directory (CVM-644)

**Comment by olifre** [comment]
Hi,
any progress on this?
It does not seem to have an actual negative effect, we are running stratum 0, stratum 1 and clients with SELinux in enforcing mode without issues, but this still looks like a bug which is simple to fix.
