### ISSUE TITLE
Catalog timeouts mismatched with CVMFS default

### ISSUE THREAD

**Issue by olifre** [cvmfs/puppet-cvmfs#81]
As of:
https://github.com/cvmfs/puppet-cvmfs/commit/942b207f63fb134695a6d386b5ca6354fab24f6c
catalog timeouts are now set to 30 s. 
However, checking upstream code:
https://github.com/cvmfs/cvmfs/blob/bfceb7b8fa4a98e27c0409fffe33987e42642478/cvmfs/server/cvmfs_server_apache.sh#L279
and also what a fresh install creates, I see:
```
    # 60 seconds and below is not cached at all by Squid default settings
    ExpiresByType application/x-cvmfs "access plus 61 seconds"
    ExpiresByType application/json    "access plus 61 seconds"
```
so this new default of 30 s seems to mismatch upstream and be a bad idea for default squid configurations.

**Comment by traylenator** [comment]
At the very least we make it a configuration with default. I think 30 may have been introduced locally here.

**Comment by traylenator** [comment]
@olifre how does https://github.com/cvmfs/puppet-cvmfs/pull/82 look to you?

**Comment by olifre** [comment]
@traylenator This looks very good, especially to have it configurable! 
Many thanks! :+1:
