### ISSUE TITLE
Replace erwbgy/limits with actively maintained module

### ISSUE THREAD

**Issue by XMol** [cvmfs/puppet-cvmfs#95]
Hello,

this module explicitly depends on the [erwbgy/limits](https://forge.puppet.com/erwbgy/limits) module, which hasn't been updated for _seven years_ and won't be any time soon! Please consider moving to a different module that is actively maintained, e.g [saz/limits](https://forge.puppet.com/saz/limits).

Best regards,
Xavier Mol.

**Comment by traylenator** [comment]
Makes sense.

**Comment by XMol** [comment]
Hi [Steve]( @traylenator ),

any chance someone from CERNOps will take care of this? Or are you waiting for a PR?

Best regards,  
Xavier.

**Comment by XMol** [comment]
Thanks Steve,

this is also a way to solve the dependency issue. 🙂 

Ciao,
Xavier.
