### ISSUE TITLE
cvmfs-fsck.timer ist not enabled

### ISSUE THREAD

**Issue by olifre** [cvmfs/puppet-cvmfs#99]
After rebooting a client machine, I find in the first Puppet run:
```
Notice: /Stage[main]/Cvmfs::Fsck/Systemd::Unit_file[cvmfs-fsck.timer]/Service[cvmfs-fsck.timer]/ensure: ensure changed 'stopped' to 'running' (corrective)
Info: /Stage[main]/Cvmfs::Fsck/Systemd::Unit_file[cvmfs-fsck.timer]/Service[cvmfs-fsck.timer]: Unscheduling refresh on Service[cvmfs-fsck.timer]
```
It seems the `cvmfs-fsck.timer` is deployed, but not enabled, so Puppet needs to re-activate it after each machine reboot. 

Should we also add `enable => true` here?
https://github.com/cvmfs/puppet-cvmfs/blob/ca6eb1588ffd18c4fb01aad9866662cd4a19f5ab/manifests/fsck.pp#L19-L26

**Comment by traylenator** [comment]
Yes it should be added.
